//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CybersportTournament
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchList
    {
        public MatchList(int IDMatch, int IDTournament)
        {
            this.IDMatch = IDMatch;
            this.IDTournament = IDTournament;
        }
        public int ID { get; set; }
        public int IDMatch { get; set; }
        public int IDTournament { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Tournaments Tournaments { get; set; }
    }
}
