//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CybersportTournament
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayersList
    {
        public PlayersList(int IDTeam, int IDPlayer)
        {
            this.IDTeam = IDTeam;
            this.IDPlayer = IDPlayer;
        }
        public int ID { get; set; }
        public int IDPlayer { get; set; }
        public int IDTeam { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
