//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CybersportTournament
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamsList(int IDTournament, int IDTeam, int NumberTeamList)
        {
            this.IDTournament = IDTournament;
            this.IDTeam = IDTeam;
            this.NumberTeamList = NumberTeamList;
            this.MatchesResults = new HashSet<MatchesResults>();
        }
    
        public int ID { get; set; }
        public int IDTournament { get; set; }
        public int IDTeam { get; set; }
        public int NumberTeamList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchesResults> MatchesResults { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual Tournaments Tournaments { get; set; }
    }
}
